# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'text4shell-vuln'
  repository: 'aaronm-sysdig/text4shell-docker'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile-vuln'
        repository: '$(repository)'
        tags: |
          $(tag)
    - task: Sysdig@1
      inputs:
        sysdigurl: 'https://app.au1.sysdig.com'
        apikey: 'cf224533-3ba6-4085-a579-5556272efa3b'
        # image: '$(imageName):$(tag)'
        image: '$(Build.Repository.Name)/$(ImageName):$(Build.BuildNumber)'
        failBuild: true
        verbose: true
